SELECT DATE_FORMAT(o1.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, o1.PRODUCT_ID, o1.USER_ID, o1.SALES_AMOUNT
FROM (
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE MONTH(SALES_DATE) = 3 AND YEAR(SALES_DATE) = 2022
) AS o1
ORDER BY o1.SALES_DATE ASC, o1.PRODUCT_ID ASC, o1.USER_ID ASC;